# Generated by Django 2.1.15 on 2020-05-20 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_like_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='like_users',
            new_name='liked_users',
        ),
    ]
