# Generated by Django 2.1.15 on 2020-05-24 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20200520_2035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-vote_average']},
        ),
    ]
